language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: hiredis
      latex: false
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      latex: false

after_success:
  - if [[ "${R_CODECOV}" ]]; then ./scripts/codecov.R; fi
